### ISSUE TITLE
Convert to installable Python module/package via setuptools?

### ISSUE THREAD

**Issue by timClicks** [TheCacophonyProject/cacophony-processing#15]
Would it make sense to make this installable via including a `setup.py` file? 

Should make it easier to integrate with integrated tools? `processing.main()` could also be added to the system's `$PATH` more easily via a entry points

**Comment by mjs** [comment]
Yes, a setup.py would definitely be nice to have. The code in this repo was rather hastily thrown together I'm afraid.

Note that we plane on deploying this with [dh-virtualenv](https://dh-virtualenv.readthedocs.io/en/latest/) soon, at which point we absolutely need a setup.py.

**Comment by mjs** [comment]
Also note, that I have a bunch of big changes to this repo in the works (almost done) which cleans up the code somewhat and adds support for processing audio uploads (which is currently being handled in a silly way).
