### ISSUE TITLE
Moving thermal processing into it's configuration section

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/cacophony-processing#54]
Right now all the options related to thermal video processing are at the top level in processing.yaml. These should really live in a `thermal` section.

**Comment by gferraro** [comment]
Sections relating to thermal

https://github.com/TheCacophonyProject/cacophony-processing/blob/b18b90ed34c6d67388ee370b8e508788d3b24cff/processing_TEMPLATE.yaml#L16-L59
